// <auto-generated />
using System;
using Lx.Infrastruct.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

namespace Lx.Infrastruct.Data.Migrations
{
    [DbContext(typeof(LxContext))]
    [Migration("20200821014351_Init_20200821")]
    partial class Init_20200821
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("Lx.Domain.Models.SystemManager.LoginRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<string>("Area")
                        .HasColumnName("AREA")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Brower")
                        .HasColumnName("BROWER")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnName("CREATETIME")
                        .HasColumnType("date");

                    b.Property<string>("Ip")
                        .HasColumnName("IP")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("LastUpdateTime")
                        .HasColumnName("LASTUPDATETIME")
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("MerchantId")
                        .HasColumnName("MERCHANTID");

                    b.Property<string>("Os")
                        .HasColumnName("OS")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id")
                        .HasName("IDX_LOGIN_RECORD_ID");

                    b.HasIndex("CreateTime")
                        .HasName("IDX_LOGIN_RECORD_CREATETIME");

                    b.HasIndex("MerchantId")
                        .IsUnique()
                        .HasName("IDX_LOGIN_RECORD_MERCHANTID");

                    b.ToTable("LOGIN_RECORD");
                });

            modelBuilder.Entity("Lx.Domain.Models.SystemManager.MerchantsAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<string>("Avatar")
                        .HasColumnName("AVATAR")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnName("CREATETIME")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnName("EMAIL")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("LastUpdateTime")
                        .HasColumnName("LASTUPDATETIME")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnName("NICKNAME")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("PassWord")
                        .HasColumnName("PASSWORD")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Phone")
                        .HasColumnName("PHONE")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(32);

                    b.HasKey("Id");

                    b.HasIndex("CreateTime")
                        .HasName("IDX_MERCHANT_ACCOUNT_CTIME");

                    b.HasIndex("NickName")
                        .HasName("IDX_MERCHANT_ACCOUNT_NICKNAME");

                    b.HasIndex("Phone")
                        .HasName("IDX_MERCHANT_ACCOUNT_PHONE");

                    b.ToTable("MERCHANT_ACCOUNT");
                });

            modelBuilder.Entity("Lx.Domain.Models.SystemManager.LoginRecord", b =>
                {
                    b.HasOne("Lx.Domain.Models.SystemManager.MerchantsAccount", "MerchantsAccount")
                        .WithMany("LoginRecord")
                        .HasForeignKey("MerchantId")
                        .HasConstraintName("FK_MERCHANTID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
